#!/usr/bin/env node
// Generates HomeBridge.Net's typed HAP catalog (Services.g.cs / Characteristics.g.cs) by
// introspecting hap-nodejs. Run after bumping the hap-nodejs dependency to keep pace with HomeKit.
//
//   npm install && node generate.js [outputDir]
//
// outputDir defaults to ../../src/HomeBridge.Net/Generated
const fs = require('fs');
const path = require('path');
const hap = require('hap-nodejs');

const hapVersion = require('hap-nodejs/package.json').version;
const outDir = process.argv[2]
  ? path.resolve(process.argv[2])
  : path.resolve(__dirname, '../../src/HomeBridge.Net/Generated');

// HAP value format -> C# type used in CharacteristicType<T>.
function clrType(format) {
  switch (format) {
    case 'bool': return 'bool';
    case 'int':
    case 'uint8':
    case 'uint16':
    case 'uint32': return 'int';
    case 'uint64': return 'long';
    case 'float': return 'double';
    case 'string':
    case 'tlv8':
    case 'data': return 'string';
    default: return 'string';
  }
}

const CS_KEYWORDS = new Set(['abstract','as','base','bool','break','byte','case','catch','char','checked','class','const','continue','decimal','default','delegate','do','double','else','enum','event','explicit','extern','false','finally','fixed','float','for','foreach','goto','if','implicit','in','int','interface','internal','is','lock','long','namespace','new','null','object','operator','out','override','params','private','protected','public','readonly','ref','return','sbyte','sealed','short','sizeof','stackalloc','static','string','struct','switch','this','throw','true','try','typeof','uint','ulong','unchecked','unsafe','ushort','using','virtual','void','volatile','while']);

function ident(name) {
  // HAP keys are PascalCase identifiers; guard against C# keywords / leading digits anyway.
  let id = name.replace(/[^A-Za-z0-9_]/g, '_');
  if (/^[0-9]/.test(id)) id = '_' + id;
  if (CS_KEYWORDS.has(id)) id = '@' + id;
  return id;
}

function header(kind, count) {
  return `// <auto-generated>
//     Generated from hap-nodejs ${hapVersion} by tools/hap-catalog-gen. Do not edit by hand.
//     ${count} ${kind}. Regenerate with: node tools/hap-catalog-gen/generate.js
// </auto-generated>
#nullable enable
namespace HomeBridge.Net;
`;
}

function pascalFromUpperSnake(s) {
  return s.split('_')
    .filter(Boolean)
    .map(part => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
    .join('');
}

// A characteristic with named integer constants on its class (e.g. OFF=0, HEAT=1, ...) becomes a
// typed C# enum named after the characteristic. Returns the enum members or null.
function enumMembersFor(ctor) {
  const members = [];
  const seen = new Set();
  for (const sk of Object.getOwnPropertyNames(ctor)) {
    const v = ctor[sk];
    // HAP value constants are ALL-CAPS integer statics (excludes UUID which is a string).
    if (typeof v === 'number' && Number.isInteger(v) && sk === sk.toUpperCase() && /[A-Z]/.test(sk)) {
      let name = ident(pascalFromUpperSnake(sk));
      if (seen.has(name)) continue;
      seen.add(name);
      members.push({ name, value: v });
    }
  }
  return members.length >= 1 ? members : null;
}

const INT_FORMATS = new Set(['int', 'uint8', 'uint16', 'uint32']);

// ---- Characteristics -----------------------------------------------------
const Ch = hap.Characteristic;
const chars = [];
const enums = [];
let chSkipped = 0;
for (const key of Object.keys(Ch).filter(k => typeof Ch[k] === 'function')) {
  const ctor = Ch[key];
  let format;
  try {
    const inst = new ctor();
    format = inst.props && inst.props.format;
  } catch {
    chSkipped++;
    continue;
  }
  if (!format) { chSkipped++; continue; }

  let members = INT_FORMATS.has(format) ? enumMembersFor(ctor) : null;
  if (members) {
    const enumName = ident(key);
    enums.push({ name: enumName, members });
    chars.push({ key, type: enumName });
  } else {
    chars.push({ key, type: clrType(format) });
  }
}
chars.sort((a, b) => a.key.localeCompare(b.key));
enums.sort((a, b) => a.name.localeCompare(b.name));

let chOut = header('characteristics', chars.length) +
  `\n/// <summary>Built-in HAP characteristic types, typed by value. Resolved by name at runtime.</summary>\n` +
  `public static class Characteristics\n{\n`;
for (const c of chars) {
  chOut += `    public static readonly CharacteristicType<${c.type}> ${ident(c.key)} = new("${c.key}");\n`;
}
chOut += `}\n`;

// ---- Characteristic enums ------------------------------------------------
let enumOut = header('characteristic enums', enums.length) +
  `\n`;
for (const e of enums) {
  const maxVal = Math.max(...e.members.map(m => m.value));
  const underlying = maxVal > 2147483647 ? ' : long' : '';
  enumOut += `/// <summary>Allowed values for the <c>${e.name}</c> characteristic.</summary>\n`;
  enumOut += `public enum ${e.name}${underlying}\n{\n`;
  for (const m of e.members) {
    enumOut += `    ${m.name} = ${m.value},\n`;
  }
  enumOut += `}\n\n`;
}

// ---- Services ------------------------------------------------------------
const Sv = hap.Service;
const services = Object.keys(Sv).filter(k => typeof Sv[k] === 'function').sort((a, b) => a.localeCompare(b));

let svOut = header('services', services.length) +
  `\n/// <summary>Built-in HAP service types. Resolved by name at runtime.</summary>\n` +
  `public static class Services\n{\n`;
for (const s of services) {
  svOut += `    public static readonly ServiceType ${ident(s)} = new("${s}");\n`;
}
svOut += `}\n`;

// ---- Accessory categories ------------------------------------------------
const catSeen = new Set();
const categories = Object.entries(hap.Categories)
  .filter(([, v]) => typeof v === 'number')
  .map(([k, v]) => ({ name: ident(pascalFromUpperSnake(k)), value: v }))
  .filter(c => !catSeen.has(c.name) && catSeen.add(c.name))
  .sort((a, b) => a.value - b.value);

let catOut = header('accessory categories', categories.length) +
  `\n/// <summary>HomeKit accessory categories (icon/type hint). Set on a created accessory.</summary>\n` +
  `public enum AccessoryCategory\n{\n`;
for (const c of categories) {
  catOut += `    ${c.name} = ${c.value},\n`;
}
catOut += `}\n`;

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(path.join(outDir, 'Characteristics.g.cs'), chOut);
fs.writeFileSync(path.join(outDir, 'CharacteristicEnums.g.cs'), enumOut);
fs.writeFileSync(path.join(outDir, 'Services.g.cs'), svOut);
fs.writeFileSync(path.join(outDir, 'AccessoryCategory.g.cs'), catOut);

console.log(`hap-nodejs ${hapVersion}`);
console.log(`  ${enums.length} characteristic enums written`);
console.log(`  ${categories.length} accessory categories written`);
console.log(`  ${chars.length} characteristics written (${chSkipped} skipped: no parameterless ctor / no format)`);
console.log(`  ${services.length} services written`);
console.log(`  -> ${outDir}`);
